//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int ma_hd { get; set; }
        public Nullable<int> ma_nv { get; set; }
        public Nullable<int> ma_pdp { get; set; }
        public Nullable<System.DateTime> ngay_tra_phong { get; set; }
        public Nullable<int> ma_tinh_trang { get; set; }
        public Nullable<double> tien_phong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhieuDatPhong PhieuDatPhong { get; set; }
        public virtual TinhTrangHoaDon TinhTrangHoaDon { get; set; }
    }
}
