//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDatPhong()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int ma_pdp { get; set; }
        public string ma_kh { get; set; }
        public Nullable<System.DateTime> ngay_dat { get; set; }
        public Nullable<System.DateTime> ngay_vao { get; set; }
        public Nullable<System.DateTime> ngay_ra { get; set; }
        public Nullable<int> ma_phong { get; set; }
        public Nullable<int> ma_tinh_trang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual TinhTrangPhieuDatPhong TinhTrangPhieuDatPhong { get; set; }
    }
}
